In [12]:
#this is the start data
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [2]:
revenue

[14574.49,
 7606.46,
 8611.41,
 9175.41,
 8058.65,
 8105.44,
 11496.28,
 9766.09,
 10305.32,
 14379.96,
 10713.97,
 15433.5]

In [3]:
expenses

[12051.82,
 5695.07,
 12319.2,
 12089.72,
 8658.57,
 840.2,
 3285.73,
 5821.12,
 6976.93,
 16618.61,
 10054.37,
 3803.96]

In [4]:
len(revenue)

12

In [5]:
len(expenses)

12

--------------------------

In [31]:
#Profit calculation
#profit = revenue - expense
#Solution
#Calculate Profit As The Differences Between Revenue And Expenses
#profit[] lista do lucro
profit = []
profit_after_tax = []
profit_margin = []


for i in range (0, len(revenue)):
    profit.append(revenue[i] - expenses[i])
    profit_after_tax.append((revenue[i] - expenses[i]) * 0.7)
    profit_margin.append(profit_after_tax[i]/ revenue[i])
    
profit
profit_after_tax
profit_margin


[0.12116163241389578,
 0.1758995643176984,
 -0.3013969837692086,
 -0.2223352416949215,
 -0.05211096151340486,
 0.6274388558795081,
 0.49993432658216397,
 0.2827619856052934,
 0.2260844884001661,
 -0.10897492065346503,
 0.04309513653668985,
 0.5274680403019406]

In [19]:
profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [21]:
profit_after_tax

[1765.869,
 1337.9730000000002,
 -2595.4530000000004,
 -2040.0169999999996,
 -419.944,
 5085.668,
 5747.385,
 2761.479,
 2329.8729999999996,
 -1567.055000000001,
 461.71999999999895,
 8140.678]

In [22]:
#best month calculation
best_month = max(profit_after_tax)
print(best_month)

8140.678


In [23]:
#worst month calculation
worst_month = min(profit_after_tax)
print(worst_month)

-2595.4530000000004


In [29]:
#mean calculation
import numpy as np
mean_before_tax = np.mean(profit)
mean_after_tax = np.mean(profit_after_tax)
print(mean_before_tax)
print(mean_after_tax)

2500.973333333333
1750.6813333333332


In [32]:
profit_margin

[0.12116163241389578,
 0.1758995643176984,
 -0.3013969837692086,
 -0.2223352416949215,
 -0.05211096151340486,
 0.6274388558795081,
 0.49993432658216397,
 0.2827619856052934,
 0.2260844884001661,
 -0.10897492065346503,
 0.04309513653668985,
 0.5274680403019406]

In [33]:
#good_months == true when condition is reached
good_months = []
for i in range (0, len(profit_after_tax)):
    good_months.append(profit_after_tax[i] > mean_after_tax)
good_months

[True, False, False, False, False, True, True, True, True, False, False, True]

In [34]:
#bad_months == true when condition is reached
bad_months = []
for i in range (0, len(profit_after_tax)):
    bad_months.append(not profit_after_tax[i] > mean_after_tax)
bad_months

[False, True, True, True, True, False, False, False, False, True, True, False]

In [40]:
import numpy as np
revenue_1000 = np.around(revenue, decimals = 2)

In [41]:
revenue_1000

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [42]:
expenses_1000 = np.around(expenses, decimals =2)

In [43]:
expenses_1000

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [50]:
#rounding the numbers
profit_1000 = np.around(profit, decimals = 2)
profit_after_tax_1000 = np.around(profit_after_tax, decimals = 2)
profit_margin_1000 = np.around(profit_margin, decimals = 2)
best_month_1000 = np.around(best_month, decimals = 2)
worst_month_1000 = np.around(worst_month, decimals = 2)

In [45]:
profit_1000

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [71]:
#printing the results
print ("Revenue :") 
print (revenue_1000)
print ("Expenses :") 
print (expenses_1000)
print ("Profit :")
print(profit_1000)
print ("Profit after tax :")
print (profit_after_tax_1000)
print ("Profit margin :")
print (profit_margin_1000)
print ("Profit margin (%)")
print ((profit_margin_1000 * 100), "%")
print ("Good months :")
print (good_months)
print ("Bad months :")
print (bad_months)
print ("Best month :")
print (best_month_1000)
print ("Worst month :")
print (worst_month_1000)

Revenue :
[14574.49  7606.46  8611.41  9175.41  8058.65  8105.44 11496.28  9766.09
 10305.32 14379.96 10713.97 15433.5 ]
Expenses :
[12051.82  5695.07 12319.2  12089.72  8658.57   840.2   3285.73  5821.12
  6976.93 16618.61 10054.37  3803.96]
Profit :
[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]
Profit after tax :
[ 1765.87  1337.97 -2595.45 -2040.02  -419.94  5085.67  5747.38  2761.48
  2329.87 -1567.06   461.72  8140.68]
Profit margin :
[ 0.12  0.18 -0.3  -0.22 -0.05  0.63  0.5   0.28  0.23 -0.11  0.04  0.53]
Profit margin (%)
[ 12.  18. -30. -22.  -5.  63.  50.  28.  23. -11.   4.  53.] %
Good months :
[True, False, False, False, False, True, True, True, True, False, False, True]
Bad months :
[False, True, True, True, True, False, False, False, False, True, True, False]
Best month :
8140.68
Worst month :
-2595.45
